name: Python linting

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Anaconda environment
      run: |
        wget https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh
        bash Anaconda3-2019.07-Linux-x86_64.sh -b
        rm Anaconda3-2019.07-Linux-x86_64.sh
        export PATH="/home/runner/anaconda3/bin:$PATH"
        conda update conda
        conda update anaconda
        conda update --all
        conda env create --file=environment.yml
        conda init bash
    - name: Lint with pylint
      run: |
        PYLINT_VER=$(grep pylint environment.yml | cut -d = -f2)
        pip install pylint==2.9.6
        export PYTHONPATH=${pwd}
        pylint **/*.py
    - name: Lint with flake8
      run: |
        FLAKE8_VER=$(grep flake8 environment.yml | cut -d = -f2)
        pip install flake8==${FLAKE8_VER}
        export PYTHONPATH=${pwd}
        flake8 --count --statistics
