name: Pytesting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Anaconda environment
      run: |
        wget https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh
        bash Anaconda3-2019.07-Linux-x86_64.sh -b
        rm Anaconda3-2019.07-Linux-x86_64.sh
        export PATH="/home/runner/anaconda3/bin:$PATH"
        conda update conda
        conda update anaconda
        conda update --all
        conda env create --file=environment.yml
        conda init bash
    - name: Run tests
      run: |
        source /home/runner/anaconda3/etc/profile.d/conda.sh
        source ~/.bashrc
        conda activate interstellar
        export PYTHONPATH=$(pwd)
        pytest
